/**:
  ros__parameters:
    serial_port: "/dev/ttyUSB0"
    serial_port_baud_rate: 460800
    ntrip_ip: "212.156.70.42"
    ntrip_user_name: "K0734151301"
    ntrip_password: "GzMSQg"
    ntrip_mount_point: "VRSRTCM31"
    ntrip_port: 2101
    ntrip_location_lat: 41.018893949
    ntrip_location_lon: 28.890924848
    publish_ros_rtcm_active: true
    debug: true
